import {
  Code2,
  Database,
  Globe,
  Palette,
  Server,
  GitBranch,
  Cloud,
  Terminal,
  Layers,
  Zap,
  FileCode,
} from "lucide-react";

export const technologies = [
  // Frontend - Cards grandes
  {
    name: "React",
    category: "Frontend",
    icon: Code2,
    description: "Biblioteca para crear interfaces de usuario interactivas",
    color: "from-blue-400 to-cyan-500",
    size: "large",
    experience: "2+ años",
  },
  {
    name: "Next.js",
    category: "Frontend",
    icon: Globe,
    description: "Framework de React para aplicaciones de producción",
    color: "from-gray-600 to-gray-900",
    size: "large",
    experience: "2+ años",
  },
  {
    name: "TypeScript",
    category: "Frontend",
    icon: FileCode,
    description: "JavaScript con tipado estático para mayor robustez",
    color: "from-blue-600 to-blue-800",
    size: "medium",
    experience: "1+ año",
  },
  {
    name: "Tailwind CSS",
    category: "Frontend",
    icon: Palette,
    description: "Framework CSS utility-first para diseño rápido",
    color: "from-teal-400 to-cyan-600",
    size: "medium",
    experience: "2+ años",
  },

  // Backend
  {
    name: "Python",
    category: "Backend",
    icon: Code2,
    description: "Lenguaje versátil para desarrollo backend",
    color: "from-yellow-500 to-orange-600",
    size: "large",
    experience: "1+ año",
  },
  {
    name: "FastAPI",
    category: "Backend",
    icon: Server,
    description: "Framework moderno para APIs rápidas con Python",
    color: "from-green-500 to-emerald-600",
    size: "medium",
    experience: "1+ año",
  },
  {
    name: "Node.js",
    category: "Backend",
    icon: Server,
    description: "Runtime de JavaScript para el servidor",
    color: "from-green-600 to-green-800",
    size: "medium",
    experience: "1+ año",
  },

  // Databases
  {
    name: "PostgreSQL",
    category: "Database",
    icon: Database,
    description: "Base de datos relacional avanzada",
    color: "from-blue-700 to-indigo-800",
    size: "medium",
    experience: "1+ año",
  },
  {
    name: "MongoDB",
    category: "Database",
    icon: Database,
    description: "Base de datos NoSQL flexible",
    color: "from-green-600 to-green-800",
    size: "small",
    experience: "1+ año",
  },
  {
    name: "SQL",
    category: "Database",
    icon: Database,
    description: "Lenguaje para gestión de bases de datos",
    color: "from-purple-600 to-purple-800",
    size: "small",
    experience: "1+ año",
  },
  {
    name: "Supabase",
    category: "Database",
    icon: Database,
    description: "Backend como servicio con PostgreSQL",
    color: "from-green-500 to-teal-600",
    size: "medium",
    experience: "6+ meses",
  },

  // Tools & DevOps
  {
    name: "Git",
    category: "Tools",
    icon: GitBranch,
    description: "Control de versiones distribuido",
    color: "from-orange-600 to-red-600",
    size: "medium",
    experience: "2+ años",
  },
  {
    name: "GitHub",
    category: "Tools",
    icon: GitBranch,
    description: "Plataforma de desarrollo colaborativo",
    color: "from-gray-600 to-gray-800",
    size: "medium",
    experience: "2+ años",
  },
  {
    name: "Terminal",
    category: "Tools",
    icon: Terminal,
    description: "Interfaz de línea de comandos",
    color: "from-gray-700 to-black",
    size: "medium",
    experience: "2+ años",
  },
  {
    name: "Vite",
    category: "Tools",
    icon: Zap,
    description: "Build tool rápido para desarrollo frontend",
    color: "from-purple-500 to-pink-600",
    size: "small",
    experience: "1+ año",
  },

  // Design & Deployment
  {
    name: "Figma",
    category: "Design",
    icon: Layers,
    description: "Herramienta de diseño colaborativo",
    color: "from-purple-500 to-pink-600",
    size: "medium",
    experience: "2+ años",
  },
  {
    name: "Vercel",
    category: "Deployment",
    icon: Cloud,
    description: "Plataforma de deployment para frontend",
    color: "from-gray-700 to-black",
    size: "small",
    experience: "2+ años",
  },
];
